package com.binance.trading.ws;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.java_websocket.WebSocket;
import org.java_websocket.handshake.ClientHandshake;
import org.java_websocket.server.WebSocketServer;

import java.net.InetSocketAddress;
import java.util.Map;
import java.util.concurrent.ConcurrentLinkedQueue;

/**
 * WebSocket server that broadcasts trading events to all connected browser clients.
 * Used by the Next.js frontend to receive real-time orders and stats.
 *
 * Message types:
 *   ORDER_CREATED  → new order generated by engine
 *   STATS_UPDATE   → engine metrics (broadcast every second)
 *   ENGINE_STATUS  → engine started / stopped
 */
public class TradingWebSocketServer extends WebSocketServer {

    private final ObjectMapper                      mapper  = new ObjectMapper();
    private final ConcurrentLinkedQueue<WebSocket>  clients = new ConcurrentLinkedQueue<>();

    public TradingWebSocketServer(int port) {
        super(new InetSocketAddress("0.0.0.0", port));
        setReuseAddr(true);
    }

    @Override
    public void onOpen(WebSocket conn, ClientHandshake handshake) {
        clients.add(conn);
        System.out.println("[WS] Client connected: " + conn.getRemoteSocketAddress()
            + "  (total=" + clients.size() + ")");
    }

    @Override
    public void onClose(WebSocket conn, int code, String reason, boolean remote) {
        clients.remove(conn);
        System.out.println("[WS] Client disconnected (total=" + clients.size() + ")");
    }

    @Override
    public void onMessage(WebSocket conn, String message) {
        // Not needed: server pushes only
    }

    @Override
    public void onError(WebSocket conn, Exception ex) {
        if (conn != null) clients.remove(conn);
    }

    @Override
    public void onStart() {
        System.out.println("[WS] WebSocket server started on port " + getPort());
    }

    public void broadcast(String type, Object data) {
        if (clients.isEmpty()) return;
        try {
            String json = mapper.writeValueAsString(Map.of("type", type, "data", data));
            for (WebSocket client : clients) {
                if (client.isOpen()) client.send(json);
            }
        } catch (Exception e) {
            // ignore serialization errors
        }
    }

    public int getClientCount() { return clients.size(); }
}
