apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "payment-api.fullname" . }}-config
  labels: {{- include "payment-api.labels" . | nindent 4 }}
data:
  PAYMENT_PORT: {{ .Values.config.paymentPort | quote }}
  PAYMENT_REPO: {{ .Values.config.paymentRepo | quote }}
  JAVA_OPTS:    {{ .Values.config.javaOpts | quote }}
